apiVersion: v1
kind: Service
metadata:
  name: restserver-service
spec:
  type: NodePort
  ports:
    - port: 9999
      targetPort: 8080
      nodePort: 31000
  selector:
    component: simplerestserver